# Change these first
owner: jonesyriffic # Your GitHub organization or username, where this repository lives
repo: gsp-sst # The name of this repository

sites:
  - name: DK - Denmark
    url: https://www.skyshowtime.com/dk/help/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /gsp-sst
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: SkyShowtime Uptime
  navbar:
    - title: EU
      href: https://jonesyriffic.github.io/gsp-eu/
    - title: Peacock
      href: https://jonesyriffic.github.io/gsp-peacock/
    - title: SST
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
